//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_HOA_DON
    {
        public int ID_CTHD { get; set; }
        public Nullable<int> ID_SP { get; set; }
        public Nullable<int> ID_KH { get; set; }
        public Nullable<int> ID_CN { get; set; }
        public Nullable<int> ID_ACC { get; set; }
        public Nullable<int> ID_HD { get; set; }
        public Nullable<int> SO_LUONG { get; set; }
        public Nullable<int> TONG_TIEN { get; set; }
        public string TRANG_THAI { get; set; }
    
        public virtual CHI_NHANH CHI_NHANH { get; set; }
        public virtual TAI_KHOAN TAI_KHOAN { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual HOA_DON HOA_DON { get; set; }
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
