//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANH_GIA
    {
        public int ID_DG { get; set; }
        public Nullable<int> ID_SP { get; set; }
        public Nullable<int> DIEM { get; set; }
        public string NOI_DUNG { get; set; }
        public string KIEM_TRA { get; set; }
        public Nullable<int> ID_ACC { get; set; }
    
        public virtual SAN_PHAM SAN_PHAM { get; set; }
        public virtual TAI_KHOAN TAI_KHOAN { get; set; }
    }
}
