//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATT.DAL
{
    using System;
    
    public partial class DoanhThuNgay_Result1
    {
        public Nullable<int> NGAY { get; set; }
        public Nullable<int> DANH_THU { get; set; }
    }
}
