//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATT.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DATTEntities : DbContext
    {
        public DATTEntities()
            : base("name=DATTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHI_NHANH> CHI_NHANH { get; set; }
        public virtual DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<CHI_TIET_HOA_DON> CHI_TIET_HOA_DON { get; set; }
        public virtual DbSet<HOA_DON> HOA_DON { get; set; }
        public virtual DbSet<THONG_TIN_SAN_PHAM> THONG_TIN_SAN_PHAM { get; set; }
        public virtual DbSet<DANH_GIA> DANH_GIAs { get; set; }
        public virtual DbSet<SAN_PHAM> SAN_PHAM { get; set; }
        public virtual DbSet<TAI_KHOAN> TAI_KHOAN { get; set; }
        public virtual DbSet<TIN_TUC> TIN_TUC { get; set; }
    
        public virtual int THEM_KHACH_VAO_HOA_DON(Nullable<int> iDKH, Nullable<int> iDAC)
        {
            var iDKHParameter = iDKH.HasValue ?
                new ObjectParameter("IDKH", iDKH) :
                new ObjectParameter("IDKH", typeof(int));
    
            var iDACParameter = iDAC.HasValue ?
                new ObjectParameter("IDAC", iDAC) :
                new ObjectParameter("IDAC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEM_KHACH_VAO_HOA_DON", iDKHParameter, iDACParameter);
        }
    
        public virtual int CAP_NHAT_GIAO_HANG(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CAP_NHAT_GIAO_HANG", iDParameter);
        }
    
        public virtual ObjectResult<DoanhThuDanhMuc_Result1> DoanhThuDanhMuc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DoanhThuDanhMuc_Result1>("DoanhThuDanhMuc");
        }
    
        public virtual ObjectResult<DoanhThuNgay_Result1> DoanhThuNgay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DoanhThuNgay_Result1>("DoanhThuNgay");
        }
    
        public virtual ObjectResult<DoanhThuThang_Result1> DoanhThuThang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DoanhThuThang_Result1>("DoanhThuThang");
        }
    
        public virtual ObjectResult<Nullable<int>> TAM_TINH(Nullable<int> aCC)
        {
            var aCCParameter = aCC.HasValue ?
                new ObjectParameter("ACC", aCC) :
                new ObjectParameter("ACC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("TAM_TINH", aCCParameter);
        }
    }
}
