//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAN_PHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAN_PHAM()
        {
            this.CHI_TIET_HOA_DON = new HashSet<CHI_TIET_HOA_DON>();
            this.DANH_GIA = new HashSet<DANH_GIA>();
            this.TIN_TUC = new HashSet<TIN_TUC>();
            this.THONG_TIN_SAN_PHAM = new HashSet<THONG_TIN_SAN_PHAM>();
        }
    
        public int ID_SP { get; set; }
        public string THUONG_HIEU { get; set; }
        public string DANH_MUC { get; set; }
        public string TEN_SAN_PHAM { get; set; }
        public string THONG_TIN_TONG_QUAT { get; set; }
        public Nullable<int> GIA { get; set; }
        public string ANH { get; set; }
        public Nullable<int> GIAM_GIA { get; set; }
        public Nullable<int> SO_LUONG_TON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_HOA_DON> CHI_TIET_HOA_DON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANH_GIA> DANH_GIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIN_TUC> TIN_TUC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONG_TIN_SAN_PHAM> THONG_TIN_SAN_PHAM { get; set; }
    }
}
