//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONG_TIN_CUA_HANG
    {
        public string TEN_CUA_HANG { get; set; }
        public string FB { get; set; }
        public string TIKTOK { get; set; }
        public string YOUTUBE { get; set; }
    }
}
