//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIN_TUC
    {
        public int ID_DMB { get; set; }
        public Nullable<int> ID_SP { get; set; }
        public string ANH { get; set; }
        public string TIEU_DE { get; set; }
        public string NOI_DUNG { get; set; }
    
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
